# Generated by Django 6.0.6 on 2026-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cuisine', models.CharField(blank=True, max_length=255)),
                ('price_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('vibe', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('visited', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('visited_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
