# Generated by Django 6.0.6 on 2026-07-09 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_follow_userrestaurant_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_photos/')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurants.userrestaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
